version: '3'
services:
    index_php:
        container_name: index-php
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/var/www/html
            - ./docker/memory.ini:/usr/local/etc/php/conf.d/memory.ini
        networks:
            - index
        depends_on:
            - index_db

    index_nginx:
      container_name: index-nginx
      hostname: nginx
      image: nginx:1.19
      restart: unless-stopped
      depends_on:
        - index_php
      ports:
        - '${APP_PORT:-80}:80'
      volumes:
        - .:/var/www/html
        - ./docker/virtualhost.conf:/etc/nginx/conf.d/default.conf
      networks:
        - index

    index_db:
        container_name: index-db
        image: 'mariadb:10.5.8'
        restart: always
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
        volumes:
            - 'indexmysql:/var/lib/mysql'
        networks:
            - index
networks:
    index:
        driver: bridge
volumes:
    indexmysql:
        driver: local
